version: '3.8'
services:
  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: fr
      POSTGRES_USER: fr-user
      POSTGRES_PASSWORD: 123456
    ports:
      - 5432:5432